<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Body>
    <ns0:MasterDataUpdateResponseEnvelope xmlns:ns0="urn:nedu:edsn:data:masterdataupdateresponse:2:standard">
      <ns0:EDSNBusinessDocumentHeader>
        <ns0:CreationTimestamp>2024-09-20T16:56:04.535+02:00</ns0:CreationTimestamp>
        <ns0:MessageID>41992543-5832-4258-8ada-42238934a603</ns0:MessageID>
        <ns0:Destination>
          <ns0:Receiver>
            <ns0:Authority>EAN.UCC</ns0:Authority>
            <ns0:ContactTypeIdentifier>DDQ_O</ns0:ContactTypeIdentifier>
            <ns0:ReceiverID>8712423034372</ns0:ReceiverID>
          </ns0:Receiver>
        </ns0:Destination>
        <ns0:Source>
          <ns0:Authority>EAN.UCC</ns0:Authority>
          <ns0:ContactTypeIdentifier>EDSN</ns0:ContactTypeIdentifier>
          <ns0:SenderID>8712423010208</ns0:SenderID>
        </ns0:Source>
      </ns0:EDSNBusinessDocumentHeader>
      <ns0:Portaal_Content>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687110002992520</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0268010000085605</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Griftdijk</ns0:StreetName>
            <ns0:BuildingNr>252</ns0:BuildingNr>
            <ns0:ZIPCode>6515AG</ns0:ZIPCode>
            <ns0:CityName>NIJMEGEN</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687120000052782</ns0:GridArea>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716871000002</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8712423012615</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8712423011403</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>55</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>10000</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>19254</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>22263</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>13261643</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>10783828</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:MutationDate>2024-09-03</ns0:MutationDate>
            <ns0:MutationReason>DSTRMSTR</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2277262764</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:SAP>
              <ns0:EANID>871687110004327627</ns0:EANID>
            </ns0:SAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687910000514362</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0797010000060814</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Lipsstraat</ns0:StreetName>
            <ns0:BuildingNr>66</ns0:BuildingNr>
            <ns0:ZIPCode>5151RP</ns0:ZIPCode>
            <ns0:CityName>DRUNEN</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687910000219120</ns0:GridArea>
          <ns0:LocationDescription>SAP</ns0:LocationDescription>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716879000004</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8716948000010</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>1750</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>23</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>52</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>259038</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>562061</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:MutationDate>2024-09-12</ns0:MutationDate>
            <ns0:MutationReason>DSTRMSTR</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2283235261</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687910000481503</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687910000515598</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0855010000127579</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Kranenberg</ns0:StreetName>
            <ns0:BuildingNr>2</ns0:BuildingNr>
            <ns0:ZIPCode>5047TR</ns0:ZIPCode>
            <ns0:CityName>TILBURG</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687910000219120</ns0:GridArea>
          <ns0:LocationDescription>SAP</ns0:LocationDescription>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716879000004</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8716948000010</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>1750</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>30</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>68</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>219380</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>524767</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:ExternalReference>SwitchB 1.1 OVID: 3665733</ns0:ExternalReference>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>SWITCHLV</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2270829805</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687910000480124</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687110004367296</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0200010003937527</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Laan van Zodiak</ns0:StreetName>
            <ns0:BuildingNr>150</ns0:BuildingNr>
            <ns0:ZIPCode>7324BC</ns0:ZIPCode>
            <ns0:CityName>APELDOORN</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687120000052782</ns0:GridArea>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716871000002</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8712423011403</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>2000</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>0</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>0</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>589067</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>1278086</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:MutationDate>2024-09-03</ns0:MutationDate>
            <ns0:MutationReason>DSTRMSTR</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2277188495</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687110003914583</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687110004367302</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0200010003937530</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Laan van de Ram</ns0:StreetName>
            <ns0:BuildingNr>86</ns0:BuildingNr>
            <ns0:ZIPCode>7324BV</ns0:ZIPCode>
            <ns0:CityName>APELDOORN</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687120000052782</ns0:GridArea>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716871000002</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8712423011403</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>2000</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>0</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>0</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>319023</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>722235</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:ExternalReference>SwitchB 1.1 OVID: 3665740</ns0:ExternalReference>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>SWITCHLV</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2270829684</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687110003914668</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871688520000250192</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0988010000064916</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Via Raeka</ns0:StreetName>
            <ns0:BuildingNr>23</ns0:BuildingNr>
            <ns0:ZIPCode>6003NK</ns0:ZIPCode>
            <ns0:CityName>WEERT</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871688520000076884</ns0:GridArea>
          <ns0:LocationDescription>SAP</ns0:LocationDescription>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716885000005</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8714252007503</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>1750</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>21</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>43</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>292969</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>633411</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:ExternalReference>SwitchB 1.1 OVID: 3856725</ns0:ExternalReference>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>SWITCHLV</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2270830528</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:Portaal_Mutation>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>DSTRMSTR</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2274338980</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871688520000235908</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871688520000250215</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0988010000064915</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Via Laera</ns0:StreetName>
            <ns0:BuildingNr>1</ns0:BuildingNr>
            <ns0:ZIPCode>6003DZ</ns0:ZIPCode>
            <ns0:CityName>WEERT</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871688520000076884</ns0:GridArea>
          <ns0:LocationDescription>SAP</ns0:LocationDescription>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716885000005</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8714252007503</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>1750</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>22</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>46</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>292691</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>633088</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:ExternalReference>SwitchB 1.1 OVID: 3856720</ns0:ExternalReference>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>SWITCHLV</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2270832782</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:Portaal_Mutation>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>DSTRMSTR</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2274335492</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871688520000235885</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687110004367302</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0200010003937530</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Laan van de Ram</ns0:StreetName>
            <ns0:BuildingNr>86</ns0:BuildingNr>
            <ns0:ZIPCode>7324BV</ns0:ZIPCode>
            <ns0:CityName>APELDOORN</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687120000052782</ns0:GridArea>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716871000002</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8712423011403</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>2000</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>0</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>0</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>331828</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>719722</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:MutationDate>2024-09-02</ns0:MutationDate>
            <ns0:MutationReason>DSTRMSTR</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2277125650</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687110003914668</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687110004367296</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0200010003937527</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Laan van Zodiak</ns0:StreetName>
            <ns0:BuildingNr>150</ns0:BuildingNr>
            <ns0:ZIPCode>7324BC</ns0:ZIPCode>
            <ns0:CityName>APELDOORN</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687120000052782</ns0:GridArea>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716871000002</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8712423011403</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>2000</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>0</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>0</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>566345</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>1282191</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:ExternalReference>SwitchB 1.1 OVID: 3665745</ns0:ExternalReference>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>SWITCHLV</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2270829341</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687110003914583</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687910000515598</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0855010000127579</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Kranenberg</ns0:StreetName>
            <ns0:BuildingNr>2</ns0:BuildingNr>
            <ns0:ZIPCode>5047TR</ns0:ZIPCode>
            <ns0:CityName>TILBURG</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687910000219120</ns0:GridArea>
          <ns0:LocationDescription>SAP</ns0:LocationDescription>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716879000004</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8716948000010</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>1750</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>30</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>68</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>223101</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>513696</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:MutationDate>2024-09-12</ns0:MutationDate>
            <ns0:MutationReason>DSTRMSTR</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2283157670</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687910000480124</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
        <ns0:Portaal_MeteringPoint>
          <ns0:EANID>871687910000514362</ns0:EANID>
          <ns0:EDSN_AddressSearch>
            <ns0:BAG>
              <ns0:BAGID>0797010000060814</ns0:BAGID>
            </ns0:BAG>
            <ns0:StreetName>Lipsstraat</ns0:StreetName>
            <ns0:BuildingNr>66</ns0:BuildingNr>
            <ns0:ZIPCode>5151RP</ns0:ZIPCode>
            <ns0:CityName>DRUNEN</ns0:CityName>
            <ns0:Country>NL</ns0:Country>
          </ns0:EDSN_AddressSearch>
          <ns0:GridArea>871687910000219120</ns0:GridArea>
          <ns0:LocationDescription>SAP</ns0:LocationDescription>
          <ns0:MarketSegment>GVB</ns0:MarketSegment>
          <ns0:ProductType>ELK</ns0:ProductType>
          <ns0:GridOperator_Company>
            <ns0:ID>8716879000004</ns0:ID>
          </ns0:GridOperator_Company>
          <ns0:MPCommercialCharacteristics>
            <ns0:BalanceSupplier_Company>
              <ns0:ID>8712423034372</ns0:ID>
            </ns0:BalanceSupplier_Company>
            <ns0:BalanceResponsibleParty_Company>
              <ns0:ID>8714252018332</ns0:ID>
            </ns0:BalanceResponsibleParty_Company>
            <ns0:MeteringResponsibleParty_Company>
              <ns0:ID>8716948000010</ns0:ID>
            </ns0:MeteringResponsibleParty_Company>
          </ns0:MPCommercialCharacteristics>
          <ns0:MPPhysicalCharacteristics>
            <ns0:AllocationMethod>TMT</ns0:AllocationMethod>
            <ns0:ContractedCapacity>0</ns0:ContractedCapacity>
            <ns0:EnergyDeliveryStatus>ACT</ns0:EnergyDeliveryStatus>
            <ns0:EnergyFlowDirection>CMB</ns0:EnergyFlowDirection>
            <ns0:MeteringMethod>TMT</ns0:MeteringMethod>
            <ns0:PhysicalCapacity>1750</ns0:PhysicalCapacity>
            <ns0:PhysicalStatus>IBD</ns0:PhysicalStatus>
            <ns0:ProfileCategory>E3A</ns0:ProfileCategory>
            <ns0:EAEnergyConsumptionNettedOffPeak>24</ns0:EAEnergyConsumptionNettedOffPeak>
            <ns0:EAEnergyConsumptionNettedPeak>51</ns0:EAEnergyConsumptionNettedPeak>
            <ns0:EAEnergyProductionNettedOffPeak>248988</ns0:EAEnergyProductionNettedOffPeak>
            <ns0:EAEnergyProductionNettedPeak>565605</ns0:EAEnergyProductionNettedPeak>
          </ns0:MPPhysicalCharacteristics>
          <ns0:Portaal_Mutation>
            <ns0:ExternalReference>SwitchB 1.1 OVID: 3666964</ns0:ExternalReference>
            <ns0:MutationDate>2024-09-01</ns0:MutationDate>
            <ns0:MutationReason>SWITCHLV</ns0:MutationReason>
            <ns0:Dossier>
              <ns0:ID>2270830013</ns0:ID>
            </ns0:Dossier>
          </ns0:Portaal_Mutation>
          <ns0:MeteringPointGroup>
            <ns0:PAP>
              <ns0:EANID>871687910000481503</ns0:EANID>
            </ns0:PAP>
          </ns0:MeteringPointGroup>
        </ns0:Portaal_MeteringPoint>
      </ns0:Portaal_Content>
    </ns0:MasterDataUpdateResponseEnvelope>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
